spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://127.0.0.1:3306/library_1?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
      username: root
      password: 12345678
      initial-size: 5
      min-idle: 15
      max-active: 30
      remove-abandoned-timeout: 180
      max-wait: 300000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 900000
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
        allow:
      web-stat-filter:
        enabled: true
        session-stat-enable: true
        session-stat-max-count: 1000
        url-pattern: /*
      filters: stat,wall,slf4j
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000

Dify:
  token: app-pjhRYjjE0bYo5EadBQ36LDtv
  url: http://localhost/v1/chat-messages
  user: abc-123